# Generated by Django 2.2.4 on 2020-04-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=200)),
                ('bsummary', models.CharField(default=models.CharField(max_length=200), max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bclaps', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='NA', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cdesc', models.CharField(max_length=1000)),
                ('username', models.CharField(default='Anonymous', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uselessdata.Blogs')),
            ],
        ),
    ]
