# Generated by Django 2.2.4 on 2020-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='bimg',
            field=models.ImageField(blank=True, upload_to='experiments'),
        ),
    ]
