# Generated by Django 2.2.4 on 2020-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0002_blogs_bimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='end_date',
            field=models.DateTimeField(blank=True, default='2011-09-01T13:20:30+03:00', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='start_date',
            field=models.DateTimeField(blank=True, default='2011-09-01T13:20:30+03:00', null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='written_at',
            field=models.DateTimeField(default='2011-09-01T13:20:30+03:00'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2011-09-01T13:20:30+03:00', null=True),
        ),
    ]
