# Generated by Django 2.2.4 on 2020-04-08 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0003_auto_20200408_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 20, 32, 8, 319187)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 20, 32, 8, 319187)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 20, 32, 8, 319187)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 20, 32, 8, 321189)),
        ),
    ]
