# Generated by Django 2.2.4 on 2020-04-17 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0004_auto_20200408_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 17, 17, 57, 20, 826594))),
                ('message', models.CharField(default='NA', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 20, 822597)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 20, 822597)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 20, 822597)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 20, 824596)),
        ),
    ]
