# Generated by Django 2.2.4 on 2020-04-17 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0005_auto_20200417_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 46, 353077)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 46, 353077)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 46, 353077)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 57, 46, 357076)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 17, 57, 46, 358074)),
        ),
    ]
