# Generated by Django 2.2.4 on 2020-04-20 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uselessdata', '0006_auto_20200417_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 18, 24, 49, 24746)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 18, 24, 49, 25756)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 18, 24, 49, 25756)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='written_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 18, 24, 49, 28753)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 18, 24, 49, 30752)),
        ),
    ]
